name: CI

# Run manually 
on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0]

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Set up QEMU
        if: matrix.os == 'ubuntu-20.04'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
        
      - name: Get dependencies (linux)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          apt-get update -y 
          apt-get install -y libboost-all-dev
          apt-get install -y libgmp-dev
          apt-get install -y libgmp10
          apt-get install -y ocl-icd-opencl-dev
          apt-get install -y libtbb-dev
          apt-get install -y wiredtiger
        
      - name: Get dependencies (mac)
        if: matrix.os == 'macos-10.15'
        run: |
          brew install -y boost
          brew install -y gmp
          apt-get install -y tbb
          apt-get install -y wiredtiger

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS_LINUX: auto aarch64 ppc64le s390x

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
